# Generated by Django 6.0.5 on 2026-10-06 05:13

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('function_name', models.CharField(max_length=150)),
                ('function_owner', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='functions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Function',
                'verbose_name_plural': 'Function Master',
                'ordering': ['function_name'],
            },
        ),
        migrations.CreateModel(
            name='ManpowerForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('HALF_YEARLY', 'Half-Yearly'), ('YEARLY', 'Yearly')], max_length=20)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('current_fte', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('avg_processing_time', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('time_unit', models.CharField(choices=[('SECONDS', 'Seconds'), ('MINUTES', 'Minutes'), ('HOURS', 'Hours')], default='MINUTES', max_length=10)),
                ('working_hours_per_day', models.DecimalField(decimal_places=2, default=Decimal('8'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('24'))])),
                ('working_days_per_week', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('working_days_per_month', models.PositiveSmallIntegerField(default=22, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('contingency_percentage', models.DecimalField(decimal_places=2, default=Decimal('15'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('99.99'))])),
                ('volume_variation_percentage', models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('time_variation_percentage', models.DecimalField(decimal_places=2, default=Decimal('15'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('simulation_count', models.PositiveIntegerField(default=10000, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(100000)])),
                ('simulation_seed', models.PositiveIntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('daily_volume', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('processing_time_minutes', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('productive_minutes_per_fte', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('workload_minutes', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('workload_hours', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('available_capacity_minutes', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('required_fte', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('recommended_operational_fte', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fte_gap', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('operational_fte_gap', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('utilization_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Empty when Current FTE is zero (utilization undefined).', max_digits=10, null=True)),
                ('unused_capacity_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('LESS', 'Less Manpower'), ('SUFFICIENT', 'Sufficient Manpower'), ('HIGHER', 'Higher Manpower')], db_index=True, max_length=20)),
                ('high_utilization_risk', models.BooleanField(default=False)),
                ('recommendation', models.TextField(blank=True)),
                ('status_explanation', models.TextField(blank=True)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_comments', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecasts_reviewed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecasts_created', to=settings.AUTH_USER_MODEL)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecasts', to='forecasting.functionmaster')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ForecastSimulationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_required_fte', models.DecimalField(decimal_places=4, max_digits=10)),
                ('minimum_required_fte', models.DecimalField(decimal_places=4, max_digits=10)),
                ('maximum_required_fte', models.DecimalField(decimal_places=4, max_digits=10)),
                ('standard_deviation', models.DecimalField(decimal_places=4, max_digits=10)),
                ('p50_required_fte', models.DecimalField(decimal_places=4, max_digits=10)),
                ('p80_required_fte', models.DecimalField(decimal_places=4, max_digits=10)),
                ('p90_required_fte', models.DecimalField(decimal_places=4, max_digits=10)),
                ('p95_required_fte', models.DecimalField(decimal_places=4, max_digits=10)),
                ('p99_required_fte', models.DecimalField(decimal_places=4, max_digits=10)),
                ('risk_adjusted_recommended_fte', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sufficiency_probability', models.DecimalField(decimal_places=2, max_digits=6)),
                ('failure_probability', models.DecimalField(decimal_places=2, max_digits=6)),
                ('simulation_count', models.PositiveIntegerField()),
                ('histogram_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_summaries', to='forecasting.manpowerforecast')),
            ],
            options={
                'verbose_name': 'Forecast Simulation Summary',
                'verbose_name_plural': 'Forecast Simulation Summaries',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ForecastAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('SIMULATE', 'Simulation Re-run'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('UPLOAD', 'Bulk Uploaded')], max_length=20)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('forecast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='forecasting.manpowerforecast')),
            ],
            options={
                'ordering': ['-performed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProcessMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('process_name', models.CharField(max_length=200)),
                ('process_owner', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('default_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('HALF_YEARLY', 'Half-Yearly'), ('YEARLY', 'Yearly')], default='DAILY', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processes_created', to=settings.AUTH_USER_MODEL)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processes', to='forecasting.functionmaster')),
            ],
            options={
                'verbose_name': 'Process',
                'verbose_name_plural': 'Process Master',
                'ordering': ['function__function_name', 'process_name'],
            },
        ),
        migrations.AddField(
            model_name='manpowerforecast',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecasts', to='forecasting.processmaster'),
        ),
        migrations.AddConstraint(
            model_name='functionmaster',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('function_name'), name='uniq_function_name_ci', violation_error_message='A function with this name already exists.'),
        ),
        migrations.AddConstraint(
            model_name='processmaster',
            constraint=models.UniqueConstraint(models.F('function'), django.db.models.functions.text.Lower('process_name'), name='uniq_process_per_function_ci', violation_error_message='This process already exists under the selected function.'),
        ),
        migrations.AddIndex(
            model_name='manpowerforecast',
            index=models.Index(fields=['created_at'], name='forecasting_created_1edd47_idx'),
        ),
        migrations.AddIndex(
            model_name='manpowerforecast',
            index=models.Index(fields=['function', 'process'], name='forecasting_functio_3920b8_idx'),
        ),
    ]
