# Generated by Django 6.0.5 on 2026-10-05 12:45

import forecasting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manpowerforecast',
            name='run_monte_carlo',
            field=models.BooleanField(default=forecasting.models.default_run_monte_carlo, help_text='Switch off to classify manpower using the deterministic calculation only.', verbose_name='Run Monte Carlo simulation'),
        ),
    ]
