# Generated by Django 6.0.5 on 2026-10-06 05:14

import django.core.validators
import forecasting.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0002_manpowerforecast_run_monte_carlo'),
    ]

    operations = [
        migrations.AddField(
            model_name='manpowerforecast',
            name='forecast_horizon_months',
            field=models.PositiveSmallIntegerField(default=forecasting.models.default_horizon_months, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AddField(
            model_name='manpowerforecast',
            name='growth_period',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('HALF_YEARLY', 'Half-Yearly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=20),
        ),
        migrations.AddField(
            model_name='manpowerforecast',
            name='growth_rate_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Expected volume change per growth period (negative = decline, 0 = no projection).', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('-99.99')), django.core.validators.MaxValueValidator(Decimal('1000'))], verbose_name='Growth %'),
        ),
        migrations.AddField(
            model_name='manpowerforecast',
            name='projected_horizon_fte_needed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='manpowerforecast',
            name='projected_horizon_required_fte',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='manpowerforecast',
            name='projected_horizon_status',
            field=models.CharField(blank=True, choices=[('LESS', 'Less Manpower'), ('SUFFICIENT', 'Sufficient Manpower'), ('HIGHER', 'Higher Manpower')], max_length=20),
        ),
        migrations.AddField(
            model_name='manpowerforecast',
            name='projected_shortfall_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='First projected month with Less Manpower (0 = already short today).', null=True),
        ),
        migrations.AddField(
            model_name='manpowerforecast',
            name='projection_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='manpowerforecast',
            name='projection_summary',
            field=models.TextField(blank=True),
        ),
    ]
