# Generated by Django 6.0.5 on 2026-10-07 13:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0003_manpowerforecast_growth_projection'),
    ]

    operations = [
        migrations.AddField(
            model_name='manpowerforecast',
            name='aht_change_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Expected change in average handling time per AHT period (negative = faster, 0 = no change).', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('-99.99')), django.core.validators.MaxValueValidator(Decimal('1000'))], verbose_name='AHT change %'),
        ),
        migrations.AddField(
            model_name='manpowerforecast',
            name='aht_change_period',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('HALF_YEARLY', 'Half-Yearly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=20),
        ),
    ]
